version: 2.1
orbs:
  win: circleci/windows@2.4.0
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Update Repositories
          command: apt update
      - run:
          name: Install Python 3
          command: apt install python3 -y
      - run:
          name: Install pip
          command: apt install python3-pip -y
      - run:
          name: Install wheel
          command: python3 -m pip install wheel 
      - run:
          name: Install GCC
          command: apt install gcc -y
      - run:
          name: Install Wget
          command: apt install wget -y
      - run:
          name: ls
          command: ls

      - run:
          name: Install PyInstaller
          command: python3 -m pip install pyinstaller
      - run:
          name: Install GIT
          command: apt install git -y
      - run:
          name: Clone project repository
          command: git clone https://github.com/danilacasito/email-overloader.git
      - run:
          name: Build Artifact for linux-systems
          command: pyinstaller --onefile email-overloader/src/overloader.py
      - store_artifacts:
          path: dist/overloader
          destination: overloader-linux
      - run:
          name: Download GHR
          command: wget https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz
      - run:
          name: Unpack GHR
          command: tar -xvf ghr_v0.14.0_linux_amd64.tar.gz
      - run:
          name: Move GHR to actual dir
          command: mv ghr_v0.14.0_linux_amd64/ghr ./ghr
      - run:
          name: Give GHR perms
          command: chmod 755 ghr
      - run:
          name: Upload Github Release
          command: ./ghr -t ${GITHUB_TOKEN} -u  ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(./dist/overloader --version) ./dist/
  buildwin:
    executor:
      name: win/default
      size: "medium"
    steps:
      - run:
          name: Install Python
          command: choco install python -y
      - run:
          name: Install GIT
          command: choco install git -y
      - run:
          name: Install pyinstaller
          command: pip install pyinstaller
      - run:
          name: clone repo
          command: git clone https://github.com/danilacasito/email-overloader.git
      - run:
          name: Build Artifact for Windows Systems
          command: pyinstaller --onefile email-overloader/src/overloader.py
      - store_artifacts:
          path: dist/overloader.exe
          destination: overloader-win.exe

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - buildwin
